# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redc < Formula
  desc "Redc is Red Team Infrastructure Multi-Cloud Automated Deployment Tool"
  homepage "https://redc.wgpsec.org"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wgpsec/redc/releases/download/v2.0.0/redc_v2.0.0_darwin_amd64.tar.gz"
      sha256 "000a16939644839cadefbfd5d8d0eb223f3b10a96a33ca1d8b9810b8a1777677"

      def install
        bin.install "redc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wgpsec/redc/releases/download/v2.0.0/redc_v2.0.0_darwin_arm64.tar.gz"
      sha256 "2f75b5e540d6fee9b8c4fc00ee04c9331d6009b505f1499f1a9eed1620a331ee"

      def install
        bin.install "redc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wgpsec/redc/releases/download/v2.0.0/redc_v2.0.0_linux_amd64.tar.gz"
      sha256 "2c6b1004493b7c4b8bd70eb2846dbba89327be6a31cf0c412ad04aa210efeb07"
      def install
        bin.install "redc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wgpsec/redc/releases/download/v2.0.0/redc_v2.0.0_linux_arm64.tar.gz"
      sha256 "271300b4048c165c0af071400a9db88f0d325d83227bc832c666f7dcd4e1d2c1"
      def install
        bin.install "redc"
      end
    end
  end
end
