# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudsword < Formula
  desc "CloudSword is a public cloud security exploitation tool."
  homepage "https://wiki.teamssix.com/cloudsword"
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/wgpsec/cloudsword/releases/download/v0.0.2/cloudsword_v0.0.2_darwin_amd64.zip"
      sha256 "68f3336dbc81746af741352faf629a9317c3d2f134812395cecf85858113d967"

      def install
        bin.install "cloudsword"
      end
    end
    on_arm do
      url "https://github.com/wgpsec/cloudsword/releases/download/v0.0.2/cloudsword_v0.0.2_darwin_arm64.zip"
      sha256 "c26c9d6351344cca2f1dce776d5cc49816cafecc2e4d33af65f9fb3703aa104b"

      def install
        bin.install "cloudsword"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/cloudsword/releases/download/v0.0.2/cloudsword_v0.0.2_linux_amd64.zip"
        sha256 "1d85869feea45022bb46a71c562bdf36f02bf2629cce36daeafe44a9dcf571ea"

        def install
          bin.install "cloudsword"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/cloudsword/releases/download/v0.0.2/cloudsword_v0.0.2_linux_arm.zip"
        sha256 "16df3bb30de321a141543d77feadf651b567939f56dd5f865bc4a7cf722e6bf0"

        def install
          bin.install "cloudsword"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/cloudsword/releases/download/v0.0.2/cloudsword_v0.0.2_linux_arm64.zip"
        sha256 "aa4ad8140c61141f347e6e536817f1652aaff43864a744b75927228d82b12873"

        def install
          bin.install "cloudsword"
        end
      end
    end
  end
end
