# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudsword < Formula
  desc "CloudSword is a public cloud security exploitation tool."
  homepage "https://wiki.teamssix.com/cloudsword"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/wgpsec/cloudsword/releases/download/v0.0.1/cloudsword_v0.0.1_darwin_amd64.zip"
      sha256 "a9e0274f561adb6899f25ec5bfeaf70aee1aef50fa5dade4f99992bee3b203d4"

      def install
        bin.install "cloudsword"
      end
    end
    on_arm do
      url "https://github.com/wgpsec/cloudsword/releases/download/v0.0.1/cloudsword_v0.0.1_darwin_arm64.zip"
      sha256 "ab1af256e722aa2e2d54aa0c1691f56d75cf8cbc16518308f86c72e3bdc3ee9a"

      def install
        bin.install "cloudsword"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/cloudsword/releases/download/v0.0.1/cloudsword_v0.0.1_linux_amd64.zip"
        sha256 "ba654570adfdc7829b83193a13ad8a06574cee9687264efb53c3def0495017a9"

        def install
          bin.install "cloudsword"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/cloudsword/releases/download/v0.0.1/cloudsword_v0.0.1_linux_arm.zip"
        sha256 "c398afa4171fc4430db3f66595ba2eef4632ff346b54ea18a587d9a8221a5ddc"

        def install
          bin.install "cloudsword"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/cloudsword/releases/download/v0.0.1/cloudsword_v0.0.1_linux_arm64.zip"
        sha256 "9587566b3ae65188186557ff6c11a7ea1e22dde05070391fc426e28a46c5216c"

        def install
          bin.install "cloudsword"
        end
      end
    end
  end
end
