# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lc < Formula
  desc "LC (List Cloud) is a multi-cloud attack surface asset enumeration tool."
  homepage "https://wiki.teamssix.com/lc"
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/wgpsec/lc/releases/download/v1.1.0/lc_v1.1.0_darwin_amd64.tar.gz"
      sha256 "a848818d242616be77cd402790606fbdffe32bddc06b2eab6c006a1e1eebbab1"

      def install
        bin.install "lc"
      end
    end
    on_arm do
      url "https://github.com/wgpsec/lc/releases/download/v1.1.0/lc_v1.1.0_darwin_arm64.tar.gz"
      sha256 "7ae40aaa484fa34a13569991e6a0c6fe19d8981283be399d4a08f8c890510e79"

      def install
        bin.install "lc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/lc/releases/download/v1.1.0/lc_v1.1.0_linux_amd64.tar.gz"
        sha256 "48d6b43e4537382afffd856dec7aa9e733a2841cb60ec50520b14f315741c45d"

        def install
          bin.install "lc"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/lc/releases/download/v1.1.0/lc_v1.1.0_linux_arm.tar.gz"
        sha256 "a53a105e53068e3d65b88ff75d59d80dbec58c4960230d33f0793c3c2f81e7bb"

        def install
          bin.install "lc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/lc/releases/download/v1.1.0/lc_v1.1.0_linux_arm64.tar.gz"
        sha256 "03463c9a2766fbd8f36024c2d2c10d6098145883a9dd912ad932d51336640f82"

        def install
          bin.install "lc"
        end
      end
    end
  end
end
