# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lc < Formula
  desc "LC (List Cloud) is a multi-cloud attack surface asset enumeration tool."
  homepage "https://wiki.teamssix.com/lc"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/wgpsec/lc/releases/download/v1.0.1/lc_v1.0.1_darwin_amd64.tar.gz"
      sha256 "7553e5563331f81ec231e6ba94e28ed2563d0326e84d1ddbb793bfa1390eedf5"

      def install
        bin.install "lc"
      end
    end
    on_arm do
      url "https://github.com/wgpsec/lc/releases/download/v1.0.1/lc_v1.0.1_darwin_arm64.tar.gz"
      sha256 "ef016371a59d79e1e8a85a5dfd740b9146110e5f64a1f331129e12e71de43790"

      def install
        bin.install "lc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/lc/releases/download/v1.0.1/lc_v1.0.1_linux_amd64.tar.gz"
        sha256 "40764eac17d8ab9f3c0e1483c30976ddd7b8619849e1189fe8bce062c6dbaa0b"

        def install
          bin.install "lc"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/lc/releases/download/v1.0.1/lc_v1.0.1_linux_arm.tar.gz"
        sha256 "59982ffdd8e93065aca5d03e38018732933a910dcb2430ae399ef3653c994f14"

        def install
          bin.install "lc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wgpsec/lc/releases/download/v1.0.1/lc_v1.0.1_linux_arm64.tar.gz"
        sha256 "672aea13d00a492a4d5c6885c217472803e1652d67a3b64012fd743aac5b57e4"

        def install
          bin.install "lc"
        end
      end
    end
  end
end
