# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lc < Formula
  desc "LC (List Cloud) is a multi-cloud attack surface asset enumeration tool."
  homepage "https://wiki.teamssix.com/lc"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wgpsec/lc/releases/download/v0.0.1/lc_v0.0.1_darwin_amd64.tar.gz"
      sha256 "643c28c3081423da0b8057b0654f1bfc11a465cb435797172daa83542496e264"

      def install
        bin.install "lc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wgpsec/lc/releases/download/v0.0.1/lc_v0.0.1_darwin_arm64.tar.gz"
      sha256 "6e56f2803d6ee2d9e5e3d51de4a1cd49bf489529fb6e13fd166a128caf2209f0"

      def install
        bin.install "lc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wgpsec/lc/releases/download/v0.0.1/lc_v0.0.1_linux_amd64.tar.gz"
      sha256 "1eba8d1b8dfdf96c1934c54bcf4d93e872fbe04945b5f1d9c4902c25b26ca845"

      def install
        bin.install "lc"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/wgpsec/lc/releases/download/v0.0.1/lc_v0.0.1_linux_arm.tar.gz"
      sha256 "89c4c87f5aad5bf71589e089ba9e328b29087357a909dee1e3c65b6e5aa938eb"

      def install
        bin.install "lc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wgpsec/lc/releases/download/v0.0.1/lc_v0.0.1_linux_arm64.tar.gz"
      sha256 "abe8fdd54c0fb6f0c32a63f6f66c904bd42e824fb9584925c1cf3f411994567c"

      def install
        bin.install "lc"
      end
    end
  end
end
