# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redc < Formula
  desc "Redc is Red Team Infrastructure Multi-Cloud Automated Deployment Tool"
  homepage "https://redc.wgpsec.org"
  version "3.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wgpsec/redc/releases/download/v3.2.6/redc_v3.2.6_darwin_amd64.tar.gz"
      sha256 "0e14480d19a31353e71cf60013cd0fce649219eba0760cbb43c09c84f0f0c903"

      define_method(:install) do
        bin.install "redc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wgpsec/redc/releases/download/v3.2.6/redc_v3.2.6_darwin_arm64.tar.gz"
      sha256 "7c3de2769e5879b5e47ea8befa4dd7ed6ec3b17405311fef05d8a2a0008a6be1"

      define_method(:install) do
        bin.install "redc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wgpsec/redc/releases/download/v3.2.6/redc_v3.2.6_linux_amd64.tar.gz"
      sha256 "7f85eb2a2996e1ed409fd6ed62781872a636e87b17bd6c175a18e2f2aa4f9744"
      define_method(:install) do
        bin.install "redc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wgpsec/redc/releases/download/v3.2.6/redc_v3.2.6_linux_arm64.tar.gz"
      sha256 "47f39285c9e21b5e72bf7ec67c9d6a729053915af79152a064c429f6a2242485"
      define_method(:install) do
        bin.install "redc"
      end
    end
  end
end
