# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redc < Formula
  desc "Redc is Red Team Infrastructure Multi-Cloud Automated Deployment Tool"
  homepage "https://redc.wgpsec.org"
  version "3.3.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wgpsec/redc/releases/download/v3.3.8/redc_v3.3.8_darwin_amd64.tar.gz"
      sha256 "91e7832e757c13e6a98707d334251da5d4101387a14d18dc70da2ad55be3f40d"

      define_method(:install) do
        bin.install "redc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wgpsec/redc/releases/download/v3.3.8/redc_v3.3.8_darwin_arm64.tar.gz"
      sha256 "8b65fd2abf31607acfddb04feaada4b0d18879ed6f3cece9064fa7902a57024c"

      define_method(:install) do
        bin.install "redc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wgpsec/redc/releases/download/v3.3.8/redc_v3.3.8_linux_amd64.tar.gz"
      sha256 "bd4af7b6f0b88f53f245944ca7df2d1567d288ec6c5a898dc98719ae7655fc06"
      define_method(:install) do
        bin.install "redc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wgpsec/redc/releases/download/v3.3.8/redc_v3.3.8_linux_arm64.tar.gz"
      sha256 "1ecb8cf2661fb124af523127329f1dd3ea3c7005a1442904cadb5f49ad39669d"
      define_method(:install) do
        bin.install "redc"
      end
    end
  end
end
